rboom-app/config/routes.rb
RboomApp::Application.routes.draw do
  

  resources :boomerangs do

       resources :programmes do
         resources :messages
       end  
  end
  

end

rboom-app/app/models/boomerang.rb
class Boomerang < ActiveRecord::Base
	has_many :programmes
end

rboom-app/app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :programme
end

rboom-app/app/models/programme.rb
class Programme < ActiveRecord::Base
  belongs_to :boomerang
  	has_many :messages

end

rboom-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rboom-app/app/controllers/boomerangs_controller.rb
class BoomerangsController < ApplicationController

	def index
        @boomerangs = Boomerang.all
	end

def show
		
		@boomerang = Boomerang.find(params[:id])
	end


  def  edit
		
		@boomerang = Boomerang.find(params[:id])
	end

  def update
    	@boomerang= Boomerang.find(params[:id])
   
    	
    	@boomerang.update(boomerang_params)

    	redirect_to @boomerang 
   
    end


     def new
        @boomerang = Boomerang.new

    end 

    def create
        
        @boomerang  = Boomerang.new(boomerang_params)
        @boomerang.save

        redirect_to boomerangs_url
    end

     def destroy
          @boomerang = Boomerang.find(params[:id])
          @boomerang.destroy
          redirect_to boomerangs_url
    end



private 
       def boomerang_params 
        params.require(:boomerang).
                            permit(:name, :fb_name, :tel_no, :email, :contact_name,:header_file)
       end


end

rboom-app/app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	def index
		 @boomerang = Boomerang.find(params[:boomerang_id])
         @programme = Programme.find(params[:programme_id])
         @messages = @programme.messages
	end


     def new
        @programme = Programme.find(params[:programme_id])
        		@message = @programme.messages.new

    end 

  def create
        
        @new_message = Message.new(message_params)
        programme = Programme.find(params [:message.programme_id])
        @new_message.programme = programme
        @new_message.save
        redirect_to boomerang_programme_messages_path(@new_message.programme.boomerang, @programme) 

       end


private
def message_params
	  params.require(:message).
                            permit(:timelag, :message, :programme_id )
end


	
end

rboom-app/app/controllers/programmes_controller.rb
class ProgrammesController < ApplicationController

def index
	    @boomerang = Boomerang.find(params[:boomerang_id])
        @programmes = @boomerang.programmes
	end

	def show
		@boomerang = Boomerang.find(params[:boomerang_id])
		@programme = Programme.find(params[:id])
	end

end

rboom-app/app/helpers/application_helper.rb
module ApplicationHelper
end

rboom-app/app/helpers/boomerangs_helper.rb
module BoomerangsHelper
end

rboom-app/app/helpers/messages_helper.rb
module MessagesHelper
end

rboom-app/app/helpers/programmes_helper.rb
module ProgrammesHelper
end

rboom-app/app/views/boomerangs/_form.html.erb
<% form_for (@boomerang) do |b| %>
<p>
  <%= b.label :name %><br/>
  <%= b.text_field :name, autofocus: true %><br/>


  <%= b.label :contact_name %><br/>
  <%= b.text_field :contact_name, size: 20 %><br/>

   <%= b.label :fb_page%><br/>
  <%= b.text_field :fb_page , size: 35 %><br/>

  <%= b.label :tel_no %><br/>
  <%= b.text_field :tel_no, size: 10 %><br/>

  
  <%= b.label :header_file %><br/>
  <%= b.text_field :header_file, size: 15 %><br/>



</p>
<p>
  <%= b.submit %> |
  <%= link_to 'cancel', boomerangs_path %>
  </p>
  <% end %>

rboom-app/app/views/boomerangs/edit.html.erb
<h1> Edit ></H1>

<%= render 'form' %>

rboom-app/app/views/boomerangs/index.html.erb
<h1> <%= pluralize(@boomerangs.count,'Boomerang') %> </h1>
<%= link_to "Add  new Boomerang", new_boomerang_path %>


<% @boomerangs.each do |b| %>
<article>
    
    <header>
    
    	<h2> <%=  link_to(b.name, b)%> </h2>
    	<h3> <%= b.contact_name %> </h3>

    </header>
    
</b>
</b>
</b>
<p>**************************</p>

</article>
<% end %>

rboom-app/app/views/boomerangs/new.html.erb
<h1> New ></H1>

<%= render 'form' %>

rboom-app/app/views/boomerangs/show.html.erb
<h1> <%= @boomerang.name %> </h1>

<article >

   <p>
    Contact: 
   <%=  @boomerang.contact_name %>
   </p>
   <p>
    Telephone:
   <%=  @boomerang.tel_no %>
   </p>
 <p>
  Email
   <%=  @boomerang.email%>

   </p>
   <p>
    Facebook Page
   <%=  @boomerang.tel_no%>

   </p>
   Header File
   <%=  @boomerang.header_file%>
   </p>
</article>

 
 <%= link_to "All Boomerangs", boomerangs_path %> |
 <%= link_to "Edit",  edit_boomerang_path(@boomerang) %>
  
<%= link_to "Programmes ",  boomerang_programmes_path(@boomerang) %>
 bo
 <%= link_to "Delete", boomerang_path(@boomerang), method: :delete , data: {confirm: 'Are You Sure'} %>

rboom-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RboomApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

rboom-app/app/views/messages/index.html.erb
<h1> List Messages </h1>



<% @messages.each do |m| %>
<article>
    
    <header>
        <h2> <%= m.timelag %> </h2>
    	<h2> <%= m.message %> </h2>
        <h2> <%= m.type    %> </h2>
        <h3> Edit Message </h3>

    </header>
    
</b>
</b>
</b>
<p>**************************</p>

</article>

<% end %>
<%= link_to "new Message ", new_boomerang_programme_message_path(@programme.boomerang, @programme) %>

rboom-app/app/views/messages/new.html.erb
<h1> New Message </h1>

<%= form_for ([@programme.boomerang, @programme,@message]) do |m| %>


   <%= m.label :timelag %><br/>
  <%= m.number_field :timelag, autofocus: true %><br/>

  <%= m.label :message %><br/>
  

   <%= m.text_area :message, cols: 40, rows: 7 %><br/>


  <%= m.submit %>
<% end %>

rboom-app/app/views/programmes/index.html.erb
<h1> Programmes  for </h1>
<h1> <%= @boomerang.name %> </h1>
 

 <%  @programmes.each do |p|  %>
<table>
	<tr>
		<th>
			details
		</th>
       <td>
       <%=  link_to(p.name, boomerang_programme_path(p.boomerang,p)) %> 
     
       </td>
       <td>
        <%= p.id %> 
       </td>
   </tr>
</table)



 <% end %>

 
<p> END </p>

rboom-app/app/views/programmes/show.html.erb
<p>


     Name:   <%= @programme.name %>
  </p>

<P>

     Boomerang   <%= @programme.boomerang.name %>
  </p>

<p>
     ID:    <%= @programme.id %> 
   </p>

<p>
     Objective    <%= @programme.objective %> 
   </p>
<p>
     Taregt    <%= @programme.target %> 
   </p>



    	

<%= link_to @programme.boomerang.name,  boomerang_programmes_path(@programme.boomerang ) %>
<%= link_to "See Messages", boomerang_programme_messages_path(@programme.boomerang, @programme) %>